# Generated by Django 6.0.3 on 2026-03-09 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('regulation', models.CharField(choices=[('hipaa', 'HIPAA - Health Insurance Portability and Accountability Act'), ('hitech', 'HITECH Act'), ('gdpr_health', 'GDPR (Healthcare Data)'), ('osha', 'OSHA - Workplace Safety'), ('joint_commission', 'Joint Commission Standards'), ('cms', 'CMS Regulations'), ('state_regulations', 'State-Specific Regulations'), ('infection_control', 'Infection Control Standards'), ('patient_rights', 'Patient Rights & Ethics')], max_length=30)),
                ('description', models.TextField()),
                ('content', models.TextField(help_text='Training module content in HTML format')),
                ('required_score', models.IntegerField(default=80)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(default='fa-shield-alt', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='compliance.compliancemodule')),
            ],
            options={
                'verbose_name_plural': 'Compliance Quizzes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=50)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='compliance.compliancemodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
    ]
