# Generated by Django 6.0.3 on 2026-04-04 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancemodule',
            name='accreditation',
            field=models.CharField(blank=True, help_text='Accreditation body', max_length=100),
        ),
        migrations.AddField(
            model_name='compliancemodule',
            name='case_studies',
            field=models.TextField(blank=True, help_text='Relevant case studies'),
        ),
        migrations.AddField(
            model_name='compliancemodule',
            name='ce_credits',
            field=models.FloatField(default=0, help_text='Continuing education credits'),
        ),
        migrations.AddField(
            model_name='compliancemodule',
            name='interactive_elements',
            field=models.JSONField(blank=True, default=list, help_text='Interactive components'),
        ),
        migrations.AddField(
            model_name='compliancemodule',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='Learning objectives, one per line'),
        ),
        migrations.AddField(
            model_name='compliancemodule',
            name='module_type',
            field=models.CharField(choices=[('training', 'Training Module'), ('assessment', 'Assessment Only'), ('certification', 'Certification Program'), ('refresher', 'Refresher Course')], default='training', max_length=20),
        ),
        migrations.AddField(
            model_name='compliancemodule',
            name='renewal_period_months',
            field=models.IntegerField(default=12, help_text='Renewal period in months'),
        ),
        migrations.AddField(
            model_name='compliancemodule',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Target audience roles', max_length=200),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_compliance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='audit_trail',
            field=models.JSONField(blank=True, default=list, help_text='Audit trail of compliance activities'),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='compliance_score',
            field=models.FloatField(default=0, help_text='Overall compliance score'),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='quiz_attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='remediation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='remediation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='supervisor_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='time_spent_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='training_progress',
            field=models.JSONField(blank=True, default=dict, help_text='Progress tracking data'),
        ),
        migrations.AddField(
            model_name='compliancerecord',
            name='weak_areas',
            field=models.JSONField(blank=True, default=list, help_text='Areas needing improvement'),
        ),
        migrations.AlterField(
            model_name='compliancemodule',
            name='regulation',
            field=models.CharField(choices=[('hipaa', 'HIPAA - Health Insurance Portability and Accountability Act'), ('hitech', 'HITECH Act'), ('gdpr_health', 'GDPR (Healthcare Data)'), ('osha', 'OSHA - Workplace Safety'), ('joint_commission', 'Joint Commission Standards'), ('cms', 'CMS Regulations'), ('state_regulations', 'State-Specific Regulations'), ('infection_control', 'Infection Control Standards'), ('patient_rights', 'Patient Rights & Ethics'), ('data_breach', 'Data Breach Notification'), ('telehealth', 'Telehealth Compliance'), ('research_ethics', 'Research Ethics (IRB)')], max_length=30),
        ),
    ]
