# Generated by Django 6.0.3 on 2026-03-09 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hospital_name', models.CharField(default='Healthcare Institution', max_length=200)),
                ('specialty', models.CharField(choices=[('general_medicine', 'General Medicine'), ('surgery', 'Surgery'), ('pediatrics', 'Pediatrics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('orthopedics', 'Orthopedics'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('psychiatry', 'Psychiatry'), ('dermatology', 'Dermatology'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('lab_technician', 'Lab Technician'), ('administration', 'Hospital Administration')], max_length=30)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('fellowship', 'Fellowship'), ('residency', 'Residency'), ('locum', 'Locum Tenens')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior Level (5-10 years)'), ('expert', 'Expert Level (10+ years)')], default='mid', max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('credentials_required', models.TextField(blank=True, help_text='Required credentials/certifications')),
                ('salary_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('benefits', models.TextField(blank=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.hospital')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='Hospital', max_length=200)),
                ('college_name', models.CharField(default='Medical College', max_length=200)),
                ('program_type', models.CharField(choices=[('internship', 'Internship Program'), ('residency', 'Residency Program'), ('fellowship', 'Fellowship Program'), ('clinical_rotation', 'Clinical Rotation'), ('research', 'Research Collaboration'), ('recruitment', 'Direct Recruitment Pipeline')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('students_enrolled', models.IntegerField(default=0)),
                ('placement_rate', models.FloatField(default=0, help_text='Percentage')),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='core.medicalcollege')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='core.hospital')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('offered', 'Offer Made'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joblisting')),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
