# Generated by Django 6.0.3 on 2026-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='clinical_domain',
            field=models.CharField(blank=True, help_text='Clinical domain (e.g., Cardiology, Pediatrics)', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='competency_level',
            field=models.CharField(choices=[('basic', 'Basic Competency'), ('intermediate', 'Intermediate Competency'), ('advanced', 'Advanced Competency'), ('expert', 'Expert Level')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='requires_clinical_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='terminology_standard',
            field=models.CharField(blank=True, choices=[('icd10', 'ICD-10'), ('snomed_ct', 'SNOMED CT'), ('loinc', 'LOINC'), ('rxnorm', 'RxNorm'), ('cpt', 'CPT Codes')], max_length=50),
        ),
        migrations.AddField(
            model_name='assessment',
            name='validation_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='adaptive_difficulty_achieved',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='clinical_reasoning_score',
            field=models.FloatField(default=0, help_text='Score for clinical reasoning questions'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='clinical_validation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='competency_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Scores by competency area'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='recommended_next_assessments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='terminology_accuracy',
            field=models.FloatField(default=0, help_text='Accuracy in medical terminology'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='clinical_scenario',
            field=models.TextField(blank=True, help_text='Clinical context for the question'),
        ),
        migrations.AddField(
            model_name='question',
            name='competency_tag',
            field=models.CharField(blank=True, help_text='Specific competency being tested', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_weight',
            field=models.FloatField(default=1.0, help_text='Weight for adaptive testing'),
        ),
        migrations.AddField(
            model_name='question',
            name='reference_materials',
            field=models.TextField(blank=True, help_text='Reference guidelines or literature'),
        ),
        migrations.AddField(
            model_name='question',
            name='terminology_codes',
            field=models.JSONField(blank=True, default=dict, help_text='Related medical codes (ICD-10, SNOMED CT, etc.)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='category',
            field=models.CharField(choices=[('clinical_skills', 'Clinical Skills'), ('medical_coding', 'Medical Coding (ICD-10)'), ('snomed_ct', 'SNOMED CT Knowledge'), ('patient_care', 'Patient Care Procedures'), ('clinical_decision', 'Clinical Decision Making'), ('pharmacology', 'Pharmacology'), ('anatomy', 'Anatomy & Physiology'), ('emergency_medicine', 'Emergency Medicine'), ('hl7_fhir', 'HL7 FHIR Standards'), ('clinical_terminology', 'Clinical Terminology Systems'), ('diagnostic_coding', 'Diagnostic Coding'), ('procedural_coding', 'Procedural Coding')], max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('clinical_case', 'Clinical Case Study'), ('coding_exercise', 'Coding Exercise'), ('terminology_mapping', 'Terminology Mapping')], default='mcq', max_length=20),
        ),
    ]
