# Generated by Django 4.2.30 on 2026-05-14 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0002_assessment_clinical_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='category',
            field=models.CharField(choices=[('patient_care', 'Patient Care Procedures'), ('medical_terminology', 'Medical Terminology'), ('clinical_decision', 'Clinical Decision Making'), ('emergency_response', 'Emergency Response'), ('nursing_fundamentals', 'Nursing Fundamentals'), ('pharmacology', 'Pharmacology Basics'), ('icd10_coding', 'ICD-10 Medical Coding'), ('snomed_ct', 'SNOMED CT Concepts'), ('hipaa_privacy', 'HIPAA & Patient Privacy'), ('infection_control', 'Infection Control & Safety'), ('emr_records', 'Electronic Medical Records (EMR)'), ('hl7_fhir', 'HL7 FHIR Interoperability'), ('lab_procedures', 'Laboratory Procedures'), ('ethics_compliance', 'Healthcare Ethics & Compliance'), ('hospital_admin', 'Hospital Administration & Workflow')], max_length=30),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
