# Generated by Django 6.0.3 on 2026-03-09 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('standard', models.CharField(choices=[('hl7_fhir', 'HL7 FHIR'), ('hl7_v2', 'HL7 v2'), ('dicom', 'DICOM'), ('cda', 'CDA (Clinical Document Architecture)'), ('general_emr', 'General EMR Usage'), ('data_entry', 'Clinical Data Entry'), ('reporting', 'Clinical Reporting')], default='general_emr', max_length=20)),
                ('description', models.TextField()),
                ('passing_score', models.IntegerField(default=70)),
                ('time_limit_minutes', models.IntegerField(default=45)),
                ('total_questions', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMRSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Key features, comma-separated')),
                ('interoperability_standards', models.CharField(default='HL7 FHIR', max_length=200)),
                ('market_share', models.FloatField(default=0, help_text='Percentage')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='emr_systems/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'EMR System',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('certified', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emr_results', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='emr_competency.competencytest')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='emr_competency.competencytest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='competencytest',
            name='emr_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='emr_competency.emrsystem'),
        ),
    ]
