# Generated by Django 6.0.3 on 2026-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr_competency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyresult',
            name='error_rate',
            field=models.FloatField(default=0, help_text='Error rate in simulation'),
        ),
        migrations.AddField(
            model_name='competencyresult',
            name='fhir_competency_score',
            field=models.FloatField(default=0, help_text='Specific FHIR competency score'),
        ),
        migrations.AddField(
            model_name='competencyresult',
            name='next_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencyresult',
            name='practical_score',
            field=models.FloatField(default=0, help_text='Score for practical simulation component'),
        ),
        migrations.AddField(
            model_name='competencyresult',
            name='recommended_training',
            field=models.JSONField(blank=True, default=list, help_text='Recommended training modules'),
        ),
        migrations.AddField(
            model_name='competencyresult',
            name='skill_gaps',
            field=models.JSONField(blank=True, default=list, help_text='Identified skill gaps'),
        ),
        migrations.AddField(
            model_name='competencyresult',
            name='theoretical_score',
            field=models.FloatField(default=0, help_text='Score for theoretical questions'),
        ),
        migrations.AddField(
            model_name='competencyresult',
            name='time_efficiency',
            field=models.FloatField(default=0, help_text='Time-based efficiency score'),
        ),
        migrations.AddField(
            model_name='competencyresult',
            name='workflow_efficiency',
            field=models.FloatField(default=0, help_text='Efficiency in clinical workflow tasks'),
        ),
        migrations.AddField(
            model_name='competencytest',
            name='practical_component',
            field=models.BooleanField(default=False, help_text='Includes hands-on EMR simulation'),
        ),
        migrations.AddField(
            model_name='competencytest',
            name='required_certifications',
            field=models.JSONField(blank=True, default=list, help_text='Required certifications'),
        ),
        migrations.AddField(
            model_name='competencytest',
            name='simulation_scenario',
            field=models.TextField(blank=True, help_text='Description of practical simulation'),
        ),
        migrations.AddField(
            model_name='competencytest',
            name='skill_level',
            field=models.CharField(choices=[('basic', 'Basic User'), ('intermediate', 'Intermediate User'), ('advanced', 'Advanced User'), ('expert', 'Expert/Superuser')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='competencytest',
            name='test_environment',
            field=models.CharField(blank=True, help_text='Test EMR environment details', max_length=100),
        ),
        migrations.AddField(
            model_name='emrsystem',
            name='api_endpoints',
            field=models.JSONField(blank=True, default=dict, help_text='Available API endpoints'),
        ),
        migrations.AddField(
            model_name='emrsystem',
            name='certification_status',
            field=models.CharField(blank=True, help_text='ONC/other certifications', max_length=100),
        ),
        migrations.AddField(
            model_name='emrsystem',
            name='deployment_type',
            field=models.CharField(choices=[('cloud', 'Cloud-based'), ('on_premise', 'On-premise'), ('hybrid', 'Hybrid')], default='cloud', max_length=50),
        ),
        migrations.AddField(
            model_name='emrsystem',
            name='fhir_version',
            field=models.CharField(default='R4', help_text='FHIR version supported', max_length=20),
        ),
        migrations.AddField(
            model_name='emrsystem',
            name='hl7_v2_compliance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emrsystem',
            name='specialty_focus',
            field=models.CharField(blank=True, help_text='Specialty areas served', max_length=200),
        ),
        migrations.AlterField(
            model_name='competencytest',
            name='standard',
            field=models.CharField(choices=[('hl7_fhir', 'HL7 FHIR'), ('hl7_v2', 'HL7 v2'), ('dicom', 'DICOM'), ('cda', 'CDA (Clinical Document Architecture)'), ('general_emr', 'General EMR Usage'), ('data_entry', 'Clinical Data Entry'), ('reporting', 'Clinical Reporting'), ('fhir_resources', 'FHIR Resources'), ('fhir_apis', 'FHIR API Integration'), ('interoperability', 'Healthcare Interoperability'), ('clinical_workflow', 'Clinical Workflow Management'), ('patient_portal', 'Patient Portal Management')], default='general_emr', max_length=30),
        ),
    ]
