# Generated by Django 6.0.3 on 2026-03-09 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('medical_license', 'Medical License'), ('nursing_license', 'Nursing License'), ('board_certification', 'Board Certification'), ('specialty_certification', 'Specialty Certification'), ('cpr_certification', 'CPR/BLS Certification'), ('acls_certification', 'ACLS Certification'), ('pharmacy_license', 'Pharmacy License'), ('technician_certification', 'Technician Certification'), ('residency_completion', 'Residency Completion'), ('fellowship', 'Fellowship Certificate')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(max_length=200)),
                ('issuing_state', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='credentials/')),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_notes', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='credentials.credential')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
