# Generated by Django 6.0.3 on 2026-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='auto_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credential',
            name='external_verification_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='credential',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='verification_api_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='credential',
            name='verification_confidence_score',
            field=models.FloatField(default=0.0, help_text='Confidence score 0-100'),
        ),
        migrations.AddField(
            model_name='credential',
            name='verification_source',
            field=models.CharField(blank=True, help_text='Source of automatic verification', max_length=200),
        ),
    ]
