# Generated by Django 6.0.3 on 2026-03-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('general_medicine', 'General Medicine'), ('surgery', 'Surgery'), ('pediatrics', 'Pediatrics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('orthopedics', 'Orthopedics'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('psychiatry', 'Psychiatry'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('lab_technician', 'Lab Technician')], max_length=30)),
                ('region', models.CharField(default='All India', max_length=100)),
                ('predicted_demand', models.IntegerField(default=0)),
                ('predicted_supply', models.IntegerField(default=0)),
                ('predicted_shortage', models.IntegerField(default=0)),
                ('shortage_level', models.CharField(default='Low', max_length=20)),
                ('forecast_year', models.IntegerField(default=2027)),
                ('confidence_score', models.FloatField(default=0.85)),
                ('recommendations', models.TextField(blank=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkforceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('general_medicine', 'General Medicine'), ('surgery', 'Surgery'), ('pediatrics', 'Pediatrics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('orthopedics', 'Orthopedics'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('psychiatry', 'Psychiatry'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('lab_technician', 'Lab Technician')], max_length=30)),
                ('region', models.CharField(max_length=100)),
                ('demand', models.IntegerField(default=0, help_text='Number of positions needed')),
                ('supply', models.IntegerField(default=0, help_text='Number of qualified professionals available')),
                ('year', models.IntegerField(default=2026)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('avg_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('growth_rate', models.FloatField(default=0, help_text='Percentage growth')),
            ],
            options={
                'verbose_name_plural': 'Workforce Data',
                'ordering': ['year', 'quarter', 'specialty'],
            },
        ),
    ]
