# Generated by Django 6.0.3 on 2026-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastreport',
            name='certification_trends',
            field=models.JSONField(blank=True, default=dict, help_text='Certification requirement trends'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='competitive_landscape',
            field=models.TextField(blank=True, help_text='Competitive analysis'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='data_sources',
            field=models.JSONField(blank=True, default=list, help_text='Data sources used for forecasting'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='diversity_inclusion_goals',
            field=models.TextField(blank=True, help_text='Diversity and inclusion goals'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='economic_outlook',
            field=models.TextField(blank=True, help_text='Economic factors affecting forecast'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='forecast_methodology',
            field=models.CharField(choices=[('linear_regression', 'Linear Regression'), ('time_series', 'Time Series Analysis'), ('machine_learning', 'Machine Learning'), ('hybrid', 'Hybrid Model'), ('expert_opinion', 'Expert Opinion')], default='machine_learning', max_length=100),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='intervention_impact',
            field=models.JSONField(blank=True, default=dict, help_text='Impact of potential interventions'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='key_drivers',
            field=models.JSONField(blank=True, default=dict, help_text='Key factors driving the forecast'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='last_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='market_trends',
            field=models.TextField(blank=True, help_text='Relevant market trends'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='next_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='policy_impact_assessment',
            field=models.TextField(blank=True, help_text='Impact of healthcare policies'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='remote_work_impact',
            field=models.FloatField(default=0, help_text='Impact of remote/telehealth work'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list, help_text='Risk factors affecting accuracy'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='salary_projections',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Projected salary range', max_digits=10),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='scenario_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Best/worst case scenarios'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='sustainability_factors',
            field=models.JSONField(blank=True, default=dict, help_text='Sustainability and ESG factors'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='talent_pipeline',
            field=models.JSONField(blank=True, default=dict, help_text='Talent pipeline analysis'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='technological_disruptions',
            field=models.TextField(blank=True, help_text='Potential technological disruptions'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='training_requirements',
            field=models.TextField(blank=True, help_text='Training and education requirements'),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='update_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='quarterly', max_length=20),
        ),
        migrations.AddField(
            model_name='forecastreport',
            name='validation_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Model validation metrics'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='aging_population_percentage',
            field=models.FloatField(default=0, help_text='Percentage of population over 65'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='chronic_disease_prevalence',
            field=models.FloatField(default=0, help_text='Prevalence of chronic diseases'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='demographic_trends',
            field=models.JSONField(blank=True, default=dict, help_text='Demographic trend data'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='economic_factors',
            field=models.TextField(blank=True, help_text='Economic factors affecting workforce'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='healthcare_facilities',
            field=models.IntegerField(default=0, help_text='Number of healthcare facilities'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='immigration_impact',
            field=models.FloatField(default=0, help_text='Impact of immigration on workforce'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='pandemic_impact',
            field=models.FloatField(default=0, help_text='COVID-19 pandemic impact score'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='policy_changes',
            field=models.TextField(blank=True, help_text='Relevant policy changes affecting demand'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='population_served',
            field=models.IntegerField(default=0, help_text='Population served in region'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='retirement_rate',
            field=models.FloatField(default=0, help_text='Annual retirement rate'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='seasonal_variations',
            field=models.JSONField(blank=True, default=dict, help_text='Seasonal demand variations'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='technology_automation',
            field=models.FloatField(default=0, help_text='Impact of technology/automation'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='telehealth_adoption',
            field=models.FloatField(default=0, help_text='Telehealth adoption rate'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='training_capacity',
            field=models.IntegerField(default=0, help_text='Annual training capacity'),
        ),
        migrations.AddField(
            model_name='workforcedata',
            name='turnover_rate',
            field=models.FloatField(default=0, help_text='Annual turnover rate'),
        ),
        migrations.AlterField(
            model_name='forecastreport',
            name='specialty',
            field=models.CharField(choices=[('general_medicine', 'General Medicine'), ('surgery', 'Surgery'), ('pediatrics', 'Pediatrics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('orthopedics', 'Orthopedics'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('psychiatry', 'Psychiatry'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('lab_technician', 'Lab Technician'), ('physical_therapy', 'Physical Therapy'), ('respiratory_therapy', 'Respiratory Therapy'), ('medical_assisting', 'Medical Assisting'), ('healthcare_it', 'Healthcare IT')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workforcedata',
            name='specialty',
            field=models.CharField(choices=[('general_medicine', 'General Medicine'), ('surgery', 'Surgery'), ('pediatrics', 'Pediatrics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('orthopedics', 'Orthopedics'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('psychiatry', 'Psychiatry'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('lab_technician', 'Lab Technician'), ('physical_therapy', 'Physical Therapy'), ('respiratory_therapy', 'Respiratory Therapy'), ('medical_assisting', 'Medical Assisting'), ('healthcare_it', 'Healthcare IT')], max_length=30),
        ),
    ]
