# Generated by Django 6.0.3 on 2026-03-09 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scenario_type', models.CharField(choices=[('emergency', 'Emergency Response'), ('diagnosis', 'Diagnostic Scenario'), ('patient_care', 'Patient Care Management'), ('surgical', 'Surgical Decision Making'), ('medication', 'Medication Management'), ('triage', 'Triage Assessment'), ('communication', 'Patient Communication'), ('ethics', 'Ethical Dilemma')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('description', models.TextField()),
                ('patient_name', models.CharField(default='Patient', max_length=100)),
                ('patient_age', models.IntegerField(default=45)),
                ('patient_gender', models.CharField(default='Male', max_length=10)),
                ('patient_history', models.TextField(blank=True)),
                ('presenting_symptoms', models.TextField()),
                ('vital_signs', models.TextField(blank=True, help_text='JSON format vital signs data')),
                ('lab_results', models.TextField(blank=True, help_text='JSON format lab results')),
                ('correct_diagnosis', models.CharField(blank=True, max_length=200)),
                ('expected_actions', models.TextField(help_text='Expected clinical actions, one per line')),
                ('time_limit_minutes', models.IntegerField(default=30)),
                ('icon', models.CharField(default='fa-heartbeat', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scenario_type', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='SimulationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('time_taken_minutes', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='simulations.simulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('feedback_correct', models.TextField(blank=True)),
                ('feedback_incorrect', models.TextField(blank=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='simulations.simulation')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
