# Generated by Django 6.0.3 on 2026-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='adaptive_difficulty',
            field=models.BooleanField(default=False, help_text='Adaptive difficulty based on performance'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='ar_supported',
            field=models.BooleanField(default=False, help_text='Augmented Reality support available'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='clinical_guidelines',
            field=models.TextField(blank=True, help_text='Relevant clinical guidelines'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='differential_diagnosis',
            field=models.TextField(blank=True, help_text='Differential diagnosis options'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='educational_objectives',
            field=models.TextField(blank=True, help_text='Learning objectives for the simulation'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='family_history',
            field=models.TextField(blank=True, help_text='Family medical history'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='imaging_results',
            field=models.TextField(blank=True, help_text='Imaging and diagnostic test results'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Comprehensive medical history'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='medications',
            field=models.TextField(blank=True, help_text='Current medications and allergies'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='patient_complaint',
            field=models.TextField(blank=True, help_text="Chief complaint in patient's own words"),
        ),
        migrations.AddField(
            model_name='simulation',
            name='physical_exam_findings',
            field=models.TextField(blank=True, help_text='Physical examination findings'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='red_flags',
            field=models.TextField(blank=True, help_text='Critical red flags in presentation'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='scoring_rubric',
            field=models.JSONField(blank=True, default=dict, help_text='Scoring criteria for evaluation'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='social_history',
            field=models.TextField(blank=True, help_text='Social and lifestyle history'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='treatment_plan',
            field=models.TextField(blank=True, help_text='Expected treatment plan'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='vr_supported',
            field=models.BooleanField(default=False, help_text='Virtual Reality support available'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='clinical_reasoning_score',
            field=models.FloatField(default=0, help_text='Score for clinical reasoning'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='communication_score',
            field=models.FloatField(default=0, help_text='Score for patient communication'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='competency_assessment',
            field=models.JSONField(blank=True, default=dict, help_text='Assessment by competency area'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='critical_steps_correct',
            field=models.IntegerField(default=0, help_text='Number of critical steps completed correctly'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='decision_making_score',
            field=models.FloatField(default=0, help_text='Score for clinical decisions'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='difficulty_adjusted',
            field=models.BooleanField(default=False, help_text='Difficulty was adjusted during simulation'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='feedback_for_employer',
            field=models.TextField(blank=True, help_text='Feedback summary for hiring managers'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='hints_used',
            field=models.IntegerField(default=0, help_text='Number of hints used during simulation'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='hiring_recommendation',
            field=models.CharField(blank=True, choices=[('highly_recommended', 'Highly Recommended'), ('recommended', 'Recommended'), ('conditional', 'Conditional Recommendation'), ('not_recommended', 'Not Recommended')], max_length=20),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='interview_score',
            field=models.FloatField(default=0, help_text='Overall interview performance score'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='patient_outcome',
            field=models.CharField(choices=[('excellent', 'Excellent Outcome'), ('good', 'Good Outcome'), ('fair', 'Fair Outcome'), ('poor', 'Poor Outcome'), ('critical', 'Critical Outcome')], default='good', max_length=50),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='performance_trends',
            field=models.JSONField(blank=True, default=dict, help_text='Performance trend analysis'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='recommended_improvements',
            field=models.JSONField(blank=True, default=list, help_text='Areas for improvement'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='simulation_mode',
            field=models.CharField(choices=[('practice', 'Practice Mode'), ('assessment', 'Assessment Mode'), ('interview', 'Interview Mode'), ('training', 'Training Mode')], default='practice', max_length=20),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='stress_level_assessed',
            field=models.BooleanField(default=False, help_text='Stress level was assessed'),
        ),
        migrations.AddField(
            model_name='simulationattempt',
            name='time_efficiency_score',
            field=models.FloatField(default=0, help_text='Score for time management'),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='alternative_approaches',
            field=models.TextField(blank=True, help_text='Alternative acceptable approaches'),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='clinical_reasoning',
            field=models.TextField(blank=True, help_text='Clinical reasoning behind the correct answer'),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='common_errors',
            field=models.TextField(blank=True, help_text='Common mistakes to avoid'),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='critical_step',
            field=models.BooleanField(default=False, help_text='Critical step for patient safety'),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='hints_available',
            field=models.IntegerField(default=0, help_text='Number of hints available'),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='interactive_elements',
            field=models.JSONField(blank=True, default=list, help_text='Interactive components'),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='multimedia_content',
            field=models.JSONField(blank=True, default=dict, help_text='Images, videos, or audio content'),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='reference_materials',
            field=models.TextField(blank=True, help_text='Reference materials for this step'),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='required_equipment',
            field=models.TextField(blank=True, help_text='Equipment needed for this step'),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='step_type',
            field=models.CharField(choices=[('assessment', 'Patient Assessment'), ('diagnosis', 'Diagnostic Decision'), ('treatment', 'Treatment Planning'), ('communication', 'Patient Communication'), ('documentation', 'Clinical Documentation'), ('medication', 'Medication Management'), ('procedure', 'Clinical Procedure'), ('emergency', 'Emergency Response')], default='assessment', max_length=20),
        ),
        migrations.AddField(
            model_name='simulationstep',
            name='time_limit_seconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='scenario_type',
            field=models.CharField(choices=[('emergency', 'Emergency Response'), ('diagnosis', 'Diagnostic Scenario'), ('patient_care', 'Patient Care Management'), ('surgical', 'Surgical Decision Making'), ('medication', 'Medication Management'), ('triage', 'Triage Assessment'), ('communication', 'Patient Communication'), ('ethics', 'Ethical Dilemma'), ('critical_care', 'Critical Care Management'), ('pediatric', 'Pediatric Emergency'), ('cardiac', 'Cardiac Emergency'), ('trauma', 'Trauma Management')], max_length=20),
        ),
    ]
